version: "3.9"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=ukrytyzubr
      - POSTGRES_PASSWORD=DpFKdiv+3A6#eg&
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready --username=ukrytyzubr && psql --username=ukrytyzubr --list"
      timeout: 10s
      retries: 20

  minio:
    image: bitnami/minio:latest
    container_name: "minio-1"
    restart: unless-stopped
    tty: true
    environment:
      - "MINIO_ROOT_USER=ukrytyzubr"
      - "MINIO_ROOT_PASSWORD=DpFKdiv+3A6#eg&"
      - "MINIO_BROWSER=on"
      - "CONSOLE_SECURE_TLS_REDIRECT=off"
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - minio_data:/data
    networks:
      - network1

networks:
  network1:
    driver: bridge
volumes:
  minio_data:
    driver: local
