version: "3.9"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 10s
      retries: 20

  minio:
    platform: linux/arm64
    image: bitnami/minio:latest
    container_name: "minio-1"
    restart: unless-stopped
    tty: true
    environment:
      - "MINIO_ROOT_USER=admin"
      - "MINIO_ROOT_PASSWORD=12345678"
      - "MINIO_DEFAULT_BUCKETS=img-cache:none,84ccbbab-e7ca-46f9-ae3e-d8f1e3939660:none,762e26e9-858b-4cc4-b4e3-93ca4c80902e:none,a23abac4-f3f3-4a98-9db8-2904972be59f:none,38f96824-6567-4a6d-a7db-f886be19401a:none,"
      - "MINIO_BROWSER=on"
      - "CONSOLE_SECURE_TLS_REDIRECT=off"
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - minio_data:/data
    networks:
      - network1

networks:
  network1:
    driver: bridge
volumes:
  minio_data:
    driver: local
